#!/bin/bash

set -eu
exec </dev/tty

version=1.0.0
base_url=https://raw.githubusercontent.com/alberto-ferrini/linux-setup/refs/heads/main
linux_setup_home=$HOME/.linux-setup
log_file=$linux_setup_home/linux-setup.log
need_reboot="false"

echo 🔵 Linux Setup $version
echo
echo 🔵 Command STDOUT and STDERR are logged in $log_file


mkdir -p $linux_setup_home
rm -rf $log_file

echo
echo ⏳ Checking for update...
# Download the content of the file into a variable
online_content=$(curl -s $base_url/linux-setup)

# Use grep to find the line starting with 'linuxSetupVersion=' and sed to extract the value after '='
online_version=$(echo "$online_content" | grep '^version=' | sed 's/^version=//')

if [ $version = $online_version ]; then
    echo "🟢 Linux Setup is up to date"
else
    echo "🟡 Update is available (v. $online_version)"
    read -p "👉 Do you want to upgrade now? (y/n) " answer
    if [ $answer = "y" ]; then
        echo "⏳ Updating..."
        curl -sL $base_url/linux-setup -o $HOME/linux-setup
        chmod 755 $HOME/linux-setup
        $HOME/linux-setup
    fi
fi

echo
echo "📘 Git"
if ! command -v git &> /dev/null; then
    echo "🟡 Git is not installed"
    read -p "👉 Do you want to install? (y/n) " answer
    if [ $answer = "y" ]; then
        echo "⏳ Installing..."
        sudo apt-get install -y git &>> $log_file
    fi
fi
if command -v git &> /dev/null; then
    git_version=$(git --version | sed 's/.* //')
    echo "🟢 Git installed (v. $git_version)"
    git_store=$(git config --global --get credential.helper || true)
    if [ -z $git_store ]; then
        echo "🟡 Git credential storage not enabled"
        read -p "👉 Do you want to enable? (y/n) " answer
        if [ $answer = "y" ]; then
            echo "⏳ Enabling..."
            git config --global credential.helper store &>> $log_file
            echo "🟢 Git credential storage enabled"
        fi
    else
        echo "🟢 Git credential storage enabled"
    fi
fi

echo
echo "📘 Docker"
if ! command -v docker &> /dev/null; then
    echo "🟡 Docker is not installed"
    read -p "👉 Do you want to install? (y/n) " answer
    if [ $answer = "y" ]; then
        echo "⏳ Installing..."
        sudo apt remove -y docker.io docker-doc docker-compose docker-compose-v2 podman-docker containerd runc &>> $log_file
        sudo apt install -y ca-certificates &>> $log_file
        sudo DEBIAN_FRONTEND=noninteractive apt install -y tzdata &>> $log_file
        sudo install -m 0755 -d /etc/apt/keyrings &>> $log_file
        sudo curl -fsSL https://download.docker.com/linux/ubuntu/gpg -o /etc/apt/keyrings/docker.asc &>> $log_file
        sudo chmod a+r /etc/apt/keyrings/docker.asc &>> $log_file
        echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu $(. /etc/os-release && echo "$VERSION_CODENAME") stable" | sudo tee /etc/apt/sources.list.d/docker.list &>> $log_file
        sudo apt update &>> $log_file
        sudo apt install -y docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin &>> $log_file
        sudo usermod -aG docker $USER &>> $log_file
        sudo systemctl enable docker.service &>> $log_file
        sudo systemctl enable containerd.service &>> $log_file
        # newgrp docker
        need_reboot="true"
    fi
fi
if command -v docker &> /dev/null; then
    echo "🟢 Docker installed"
fi
echo
echo "🟢 Linux setup completed!"
echo
if [ $need_reboot = "true" ]; then
    read -p "👉 Do you want to reboot to apply updates? (y/n) " answer
    if [ $answer = "y" ]; then
        sudo shutdown -r now
    fi
fi
