#!/bin/bash

# Set working directory to this script directory
cd "$(dirname "$0")"

read -p "Do you want to download package information from all configured sources? (y/n): " confirm
if [[ $confirm == [yY] || $confirm == [yY][eE][sS] ]]; then
    echo "⏳ Updating..."
    sudo apt-get update
    echo "✅ Updated"
fi
echo ""

read -p "Do you want to install available upgrades of all packages currently installed on the system? (y/n): " confirm
if [[ $confirm == [yY] || $confirm == [yY][eE][sS] ]]; then
    echo "⏳ Upgrading..."
    sudo apt-get upgrade
    echo "✅ Updated"
fi
echo ""

read -p "Do you want to install Git? (y/n): " confirm
if [[ $confirm == [yY] || $confirm == [yY][eE][sS] ]]; then
    echo "⏳ Installing Git..."
    sudo apt-get install git
    echo "✅ Git installed"
    echo ""
    echo "Do you want to configure Git for credentials storage (https://stackoverflow.com/a/35942890)."
    read -p "Configure Git for credentials storage? (y/n): " confirm
    if [[ $confirm == [yY] || $confirm == [yY][eE][sS] ]]; then
        git config --global credential.helper store
        echo "✅ Git credentials storage configured"
    fi
fi
echo ""

# Docker installation script from https://docs.docker.com/engine/install/ubuntu/ and https://docs.docker.com/engine/install/linux-postinstall/
read -p "Do you want to install Docker? (y/n): " confirm
if [[ $confirm == [yY] || $confirm == [yY][eE][sS] ]]; then
    echo "⏳ Installing Docker..."
    for pkg in docker.io docker-doc docker-compose docker-compose-v2 podman-docker containerd runc; do sudo apt-get remove $pkg; done
    sudo apt-get update
    sudo apt-get install ca-certificates curl
    sudo install -m 0755 -d /etc/apt/keyrings
    sudo curl -fsSL https://download.docker.com/linux/ubuntu/gpg -o /etc/apt/keyrings/docker.asc
    sudo chmod a+r /etc/apt/keyrings/docker.asc
    echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu $(. /etc/os-release && echo "$VERSION_CODENAME") stable" | sudo tee /etc/apt/sources.list.d/docker.list >/dev/null
    sudo apt-get update
    sudo apt-get install docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
    sudo groupadd docker
    sudo usermod -aG docker $USER
    sudo systemctl enable docker.service
    sudo systemctl enable containerd.service
    echo "✅ Docker installed"
fi
echo ""

# Node.js installation script from https://nodejs.org/en/download/package-manager
read -p "Do you want to install Node.js? (y/n): " confirm
if [[ $confirm == [yY] || $confirm == [yY][eE][sS] ]]; then
    echo "⏳ Installing Node.js ..."
    curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.0/install.sh | bash
    source $HOME/.bashrc
    nvm install --lts
    nvm use --lts
    echo "✅ Node.js installed"
fi
echo ""

read -p "Do you want to install Java? (y/n): " confirm
if [[ $confirm == [yY] || $confirm == [yY][eE][sS] ]]; then
    # Installing tool for JSON parsing (used to parse JSON API HTTP response).
    echo "⏳ Installing jq..."
    sudo apt-get install jq
    echo "✅ jq installed"
    # Installing tool for auto-generated file formatting.
    echo "⏳ Installing clang-format..."
    sudo apt-get install clang-format
    echo "✅ clang-format installed"
    echo "⏳ Retrieving available Java versions..."
    # Using Adoptium API from https://api.adoptium.net/q/swagger-ui/
    javaVersions=$(curl -s https://api.adoptium.net/v3/info/available_releases | jq -c '.available_releases?|@sh' | sed 's/"//g')
    echo "✅ Available Java versions retrieved"
    # read -a JAVA_VERSIONS <<<$JAVA_VERSIONS
    # echo "${JAVA_VERSIONS[0]}"
    echo ""
    echo "Available Java versions: $javaVersions"
    read -p "Select Java version: " javaVersionDownload
    tmpDir="/tmp/$(date +%s)"
    mkdir -p $tmpDir
    curl --output-dir $tmpDir --location --remote-header-name --remote-name "https://api.adoptium.net/v3/binary/latest/$javaVersionDownload/ga/linux/x64/jdk/hotspot/normal/eclipse"
    jdkName=$(ls $tmpDir)
    mkdir -p $HOME/software/jdk
    mv $tmpDir/*.tar.gz $HOME/software/jdk
    rm -rf $tmpDir
    tar -zxvf $HOME/software/jdk/$jdkName --directory $HOME/software/jdk
    rm -f $HOME/software/jdk/$jdkName
    # jdkVersion=${jdkName#*_}
    # jdkVersion=${jdkVersion#*_}
    # jdkVersion=${jdkVersion#*_}
    # jdkVersion=${jdkVersion#*_}
    # jdkVersion=${jdkVersion%.*}
    # jdkVersion=${jdkVersion%.*}
    # jdkVersion=${jdkVersion/_/+}
fi
echo ""

mkdir -p $HOME/software/jdk
jdks=($(ls $HOME/software/jdk))
jdksLength=${#jdks[@]}
if [[ $jdksLength < 1 ]]; then
    echo "❌ No JDKs found"
    exit 1
fi
echo "JDKs found:"
for ((i = 0; i < ${jdksLength}; i++)); do
    echo "$((i + 1))) ${jdks[$i]}"
done

re='^[0-9]+$'
choose=-1

while [[ ! $choose =~ $re || $choose -le 0 || $choose -gt $jdksLength ]]; do
    read -p "Choose JDK to set to default (number): " choose
done

selectedJdk=${jdks[$((choose - 1))]}
echo "Selected JDK: $selectedJdk"

echo "⏳ Configuring setup..."
\cp -rf .setup $HOME
javaMajorVersion=${selectedJdk#*_}
javaMajorVersion=${javaMajorVersion#*-}
javaMajorVersion=${javaMajorVersion%.*}
javaMajorVersion=${javaMajorVersion%.*}
sed -i -e "s/@JAVA_MAJOR_VERSION@/$javaMajorVersion/g" "$HOME/.setup"
sed -i -e "s/@JAVA_VERSION@/$selectedJdk/g" "$HOME/.setup"

if [ ! -f $HOME/.setup-custom ]; then
    \cp -rf .setup-custom $HOME
fi

echo "✅ Setup configured"
echo ""

echo "⏳ Installing setup..."
for fileName in "$HOME/.bashrc" "$HOME/.profile"; do
    if [[ $(grep 'linux-setup customization' $fileName | wc -l) == "0" ]]; then
        echo '' >>$fileName
        echo '# BEGIN linux-setup customization' >>$fileName
        echo 'source $HOME/.setup' >>$fileName
        echo '# END linux-setup customization' >>$fileName
        echo '' >>$fileName
        echo "  ✅ $fileName updated"
    else
        echo "  🆗 $fileName already configured"
    fi
done
echo "✅ Setup installed"
echo ""
echo "⏳ Updating files..."
for element in "scripts"; do
    \cp -rf $element $HOME
    echo "  🔄 $element updated"
done
echo "✅ Files updated"
echo ""

echo "✅ Environment ready"
unset JAVA_HOME
bash
